FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/satgen
RUN g++ -o nmea2um nmea2um.c

RUN mkdir -p /deps
RUN ldd /repo/satgen/nmea2um | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/satgen/nmea2um /repo/satgen/nmea2um
ENV LD_LIBRARY_PATH=/deps
